---
ID: "cc0de02c-e367-403c-8b8f-b819b02e81a9"
Parent: "c9fd5b79-aea5-40e0-ad68-6601be6ac822"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: "/sitecore/content/hackathon/stack-overflowed/Presentation/Placeholder Settings"
BranchID: "eb881f60-3843-4a8c-a636-d3e9992f179a"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{B3BA27C7-FDFE-4676-B4B7-2BF6BFB57FD9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250308T021935Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b4a71d76-ccfb-4960-8daf-b4753fdb6aa8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T021935Z
